/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_aib42_mumblelink_MumbleLink */

#ifndef _Included_net_aib42_mumblelink_MumbleLink
#define _Included_net_aib42_mumblelink_MumbleLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_aib42_mumblelink_MumbleLink
 * Method:    setNameAndDescription
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_aib42_mumblelink_MumbleLink_setNameAndDescription
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     net_aib42_mumblelink_MumbleLink
 * Method:    setIdentityAndContext
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_aib42_mumblelink_MumbleLink_setIdentityAndContext
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     net_aib42_mumblelink_MumbleLink
 * Method:    updateMumble
 * Signature: (FFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_aib42_mumblelink_MumbleLink_updateMumble
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
